name: Deploy Love is Love TestNet Mint Page
on:
  push:
    branches: [testnet]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: npm install
      - run: npm run build
      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: ./out
          bucket: rgvart-lil-mint-testnet
          dist-id: E14PDIB9ZGNNBU
          invalidation: / *